import LogoutButton from "@/components/LogoutButton";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "articles",
  description: "Generated by articles",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div className="text-right">
        <LogoutButton />
      </div>
      {children}
    </main>
  );
}
